version: "2"

services:
  gateway:
    image: golang:1.8
    restart: on-failure
    volumes:
      - ./gateway:/go/src/github.com/dung13890/go-services/gateway
    working_dir: /go/src/github.com/dung13890/go-services/gateway
    environment:
      - GOBIN=/go/bin
    ports:
      - "3000:3000"
    links:
      - users
      - products
      - orders
    tty: true
  users:
    image: golang:1.8
    restart: on-failure
    volumes:
      - ./users:/go/src/github.com/dung13890/go-services/users
    working_dir: /go/src/github.com/dung13890/go-services/users
    environment:
      - GOBIN=/go/bin
    links:
      - mongodb
    tty: true
  products:
    image: golang:1.8
    restart: on-failure
    volumes:
      - ./products:/go/src/github.com/dung13890/go-services/products
    working_dir: /go/src/github.com/dung13890/go-services/products
    environment:
      - GOBIN=/go/bin
    links:
      - mongodb
    tty: true
  orders:
    image: golang:1.8
    restart: on-failure
    volumes:
      - ./orders:/go/src/github.com/dung13890/go-services/orders
    working_dir: /go/src/github.com/dung13890/go-services/orders
    environment:
      - GOBIN=/go/bin
    links:
      - mongodb
    tty: true
  caddy:
    image: abiosoft/caddy
    restart: always
    volumes:
     - ./caddyfile:/srv
    ports:
     - "80:80"
     - "443:443"
    links:
      - gateway
    tty: true
  mongodb:
    image: mongo
    restart: on-failure
    volumes:
      - ./mongodb:/data/db
    tty: true
